[package]
name = "check_schemas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "*"
serde_json = "*"
jsonschema = "*"
configure_validator = {path = "../configure_validator"}
